/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./public/**/*.html", "./public/**/*.js"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb8",
        "surface": "#051424",
        "on-primary-fixed": "#0f1c2c",
        "on-secondary-container": "#00311f",
        "primary": "#bac8dc",
        "surface-tint": "#bac8dc",
        "on-primary-container": "#768497",
        "surface-bright": "#2c3a4c",
        "on-surface-variant": "#c4c6cc",
        "primary-fixed-dim": "#bac8dc",
        "secondary": "#4edea3",
        "outline-variant": "#44474c",
        "secondary-container": "#00a572",
        "primary-fixed": "#d6e4f9",
        "tertiary": "#ffb95f",
        "error-container": "#93000a",
        "on-tertiary": "#472a00",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-dim": "#051424",
        "surface-container-high": "#1c2b3c",
        "on-background": "#d4e4fa",
        "surface-variant": "#273647",
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#281600",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#233143",
        "outline": "#8e9196",
        "on-surface": "#d4e4fa",
        "on-secondary": "#003824",
        "surface-container-lowest": "#010f1f",
        "inverse-surface": "#d4e4fa",
        "on-primary-fixed-variant": "#3a4859",
        "on-primary": "#243141",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#ffdad6",
        "background": "#051424",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-container": "#122131",
        "surface-container-low": "#0d1c2d",
        "inverse-primary": "#525f71",
        "on-secondary-fixed": "#002113",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#b77400",
        "primary-container": "#0d1b2a",
        "surface-container-highest": "#273647",
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
